(defface font-lock-log-error-face '((t (:foreground "red"))) "shell-mode: error" :group 'font-lock-faces)
(defface font-lock-log-in-out-face '((t (:weight bold :foreground "green"))) "shell-mode: ==> / <==" :group 'font-lock-faces)
(defface font-lock-log-separ-face '((t (:weight bold :foreground "green"))) "shell-mode: separator" :group 'font-lock-faces)
(defface font-lock-log-warning-face '((t (:foreground "orange"))) "shell-mode: warning" :group 'font-lock-faces)
(defface font-lock-perl-spd-name-face '((t (:weight normal :foreground "#000500000" :background "#E00FFFE00"))) "SPD/DDL: macro name" :group 'font-lock-faces)
(defface font-lock-shell-mode-context-face '((t (:weight bold :foreground "green" :background "gray20"))) "shell-mode: new prompt" :group 'font-lock-faces)
(defface font-lock-todo-face '((t (:weight bold :foreground "red" :background "yellow"))) "TODO marker" :group 'font-lock-faces)
(defface font-lock-wiki-bold-face '((t (:weight bold))) "wiki: bold" :group 'font-lock-faces)
(defface font-lock-wiki-head-1-face '((t (:weight bold :foreground "green"))) "wiki: header-1" :group 'font-lock-faces)
(defface font-lock-wiki-head-2-face '((t (:foreground "green"))) "wiki: header-2" :group 'font-lock-faces)
(defface font-lock-wiki-italic-face '((t (:slant italic))) "wiki: italic" :group 'font-lock-faces)
(defface font-lock-wiki-macro-face '((t (:weight bold :foreground "black" :background "cyan"))) "wiki: macro" :group 'font-lock-faces)

(defvar font-lock-log-error-face 'font-lock-log-error-face "font-lock-log-error-face")
(defvar font-lock-log-in-out-face 'font-lock-log-in-out-face "font-lock-log-in-out-face")
(defvar font-lock-log-separ-face 'font-lock-log-separ-face "font-lock-log-separ-face")
(defvar font-lock-log-warning-face 'font-lock-log-warning-face "font-lock-log-warning-face")
(defvar font-lock-perl-spd-name-face 'font-lock-perl-spd-name-face "font-lock-perl-spd-name-face")
(defvar font-lock-shell-mode-context-face 'font-lock-shell-mode-context-face "font-lock-shell-mode-context-face")
(defvar font-lock-todo-face 'font-lock-todo-face "font-lock-todo-face")
(defvar font-lock-wiki-bold-face 'font-lock-wiki-bold-face "font-lock-wiki-bold-face")
(defvar font-lock-wiki-head-1-face 'font-lock-wiki-head-1-face "font-lock-wiki-head-1-face")
(defvar font-lock-wiki-head-2-face 'font-lock-wiki-head-2-face "font-lock-wiki-head-2-face")
(defvar font-lock-wiki-italic-face 'font-lock-wiki-italic-face "font-lock-wiki-italic-face")
(defvar font-lock-wiki-macro-face 'font-lock-wiki-macro-face "font-lock-wiki-macro-face")
