(global-set-key [(control <)] 'tabbar-backward-tab)
(global-set-key [(control >)] 'tabbar-forward-tab)
(global-set-key [(control B)] 'rv_shell_f_create_new_shell_agtwbe)
(global-set-key [(control F)] 'rv_shell_f_create_new_shell_agtwfe)
(global-set-key [(control S)] 'rv_spd_f_normalize_space_between_queries)
(global-set-key [(control a)] 'mark-whole-buffer)
(global-set-key [(control c)] 'copy-region-as-kill)
(global-set-key [(control end)] 'rv_common_f_move_buffer_end)
(global-set-key [(control home)] 'rv_common_f_move_buffer_beginning)
(global-set-key [(control meta down)] 'rv_common_f_move_scroll_down)
(global-set-key [(control meta f12)] 'rv_common_f_ediff_with_previous_version)
(global-set-key [(control meta l)] 'rv_common_f_toggle_wrap_lines)
(global-set-key [(control meta left)] 'rv_common_f_move_scroll_left)
(global-set-key [(control meta q)] 'rv_common_f_goto_relative_line)
(global-set-key [(control meta right)] 'rv_common_f_move_scroll_right)
(global-set-key [(control meta s)] 'rv_common_f_sort_selection_lines)
(global-set-key [(control meta t)] 'toggle-read-only)
(global-set-key [(control meta up)] 'rv_common_f_move_scroll_up)
(global-set-key [(control next)] 'end-of-buffer)
(global-set-key [(control p)] 'rv_language_f_re_indent_buffer)
(global-set-key [(control prior)] 'beginning-of-buffer)
(global-set-key [(control q)] 'goto-line)
(global-set-key [(control return)] 'rv_common_f_turn_buffer_into_single_line)
(global-set-key [(control t)] 'rv_language_f_insert_trace)
(global-set-key [(control tab)] 'other-window)
(global-set-key [(control v)] 'yank)
(global-set-key [(control x) ?g] 'insert-register)
(global-set-key [(control x) ?x] 'copy-to-register)
(global-set-key [(control z)] 'undo)
(global-set-key [(meta b)] 'rv_common_f_rotate_buffer)
(global-set-key [(meta backspace)] 'backward-kill-word)
(global-set-key [(meta c)] 'rv_language_f_insert_header_class)
(global-set-key [(meta control tab)] 'tab-to-tab-stop)
(global-set-key [(meta delete)] 'backward-kill-word)
(global-set-key [(meta g)] 'rv_language_f_source_grep)
(global-set-key [(meta l)] 'rv_language_f_insert_separator)
(global-set-key [(meta left)] 'backward-sexp)
(global-set-key [(meta m)] 'rv_language_f_insert_header_method)
(global-set-key [(meta o)] 'rv_shell_f_create_new_shell)
(global-set-key [(meta q)] 'query-replace-regexp)
(global-set-key [(meta r)] 'rv_common_f_reload_buffer)
(global-set-key [(meta right)] 'forward-sexp)
(global-set-key [(meta s)] 'rv_common_f_save_all_buffers)
(global-set-key [(meta t)] 'rv_language_f_insert_todo)
(global-set-key [(meta u)] 'rv_language_f_update_history)
(global-set-key [(meta v)] 'rv_tmpl_f_insert_var_html)
(global-set-key [(shift meta left)] 'backward-sexp-mark)
(global-set-key [(shift meta right)] 'forward-sexp-mark)
(global-set-key [(shift tab)] 'rv_common_f_insert_tab)
(global-set-key [backspace] 'backward-delete-char-untabify)
(global-set-key [delete] 'delete-char)
(global-set-key [end] 'end-of-line)
(global-set-key [f10] 'rv_shell_f_command_apache_rotate_logs)
(global-set-key [f11] 'c-hungry-delete-forward)
(global-set-key [f12] 'rv_common_f_kill_current_buffer)
(global-set-key [f2] 'rv_common_f_clean_save)
(global-set-key [f3] 'find-file)
(global-set-key [f4] 'repeat-complex-command)
(global-set-key [f5] 'rv_common_f_load_file_under_cursor)
(global-set-key [f6] 'undo)
(global-set-key [f7] 'compile)
(global-set-key [f8] 'rv_common_f_goto_next_error)
(global-set-key [f9] 'fill-paragraph)
(global-set-key [home] 'beginning-of-line)
(global-set-key [kp-delete] 'delete-char)
(global-set-key [next] 'scroll-up)
(global-set-key [prior] 'scroll-down)
